<a href="https://colab.research.google.com/github/bkvkrll/linear-algebra/blob/main/lesson5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [1]:
import numpy as np

In [2]:
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)
 
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')


Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$$-1\begin{pmatrix}
1 & 0 \\ 
0 & 1 \\
\end{pmatrix}
\begin{pmatrix}
x1\\
x2\\
\end{pmatrix}=
\lambda
\begin{pmatrix}
x1\\
x2\\
\end{pmatrix}
$$

$$
\lambda=-1.$$

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = -2\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

In [3]:
A = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(A)
 
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
-9 = 3\cdot \lambda\\ 
9 = -3\cdot\lambda\\
-12 = -4\cdot\lambda\
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3\\
\end{cases}$$

In [4]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(A)
 
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
