<a href="https://colab.research.google.com/github/bkvkrll/linear-algebra/blob/main/lesson_6_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

In [1]:
import numpy as np

In [11]:
def gauss(A, b, n):
    rnk_A = np.linalg.matrix_rank(A)
    rnk_Ab = np.linalg.matrix_rank(np.hstack((A, b)))
    if  rnk_A == rnk_Ab == n:
        return 'Cистема имеет единственное решение'
    elif (rnk_A == rnk_Ab) and (rnk_A < n):
        return 'Cистема имеет бесконечное количество решений'
    elif rnk_A < rnk_Ab:
        return 'Cистема несовместна'

In [13]:
A = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
b = np.array([0, -2, 4]).reshape(-1, 1)
gauss(A, b, 4)

'Cистема имеет бесконечное количество решений'

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [14]:
# а)
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0]).reshape(-1, 1)
gauss(A, b, 3)

'Cистема имеет единственное решение'

In [15]:
# б)
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5]).reshape(-1, 1)
gauss(A, b, 3)

'Cистема несовместна'

In [16]:
# в)
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2]).reshape(-1, 1)
gauss(A, b, 3)

'Cистема имеет бесконечное количество решений'

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [19]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1]).reshape(-1, 1)
gauss(A, b, 4)

'Cистема имеет единственное решение'

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [20]:
# а)
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7]).reshape(-1, 1)

x1 = np.linalg.det(np.hstack((b, A[:,1].reshape(-1, 1)))) /  np.linalg.det(A)
x2 = np.linalg.det(np.hstack((A[:,0].reshape(-1, 1), b))) /  np.linalg.det(A)

In [21]:
np.linalg.solve(A, b)

array([[5.],
       [2.]])

In [22]:
# б)
A = np.array([[2, -1, 5], [1, 2, -3], [2, 4, 1]])
b = np.array([10, -2, 1]).reshape(-1, 1)
x1 = np.linalg.det(np.hstack((b, A[:,1:]))) /  np.linalg.det(A)
x2 = np.linalg.det(np.hstack((A[:,:1], b, A[:,-1:]))) /  np.linalg.det(A)
x3 = np.linalg.det(np.hstack((A[:,:2], b))) /  np.linalg.det(A)

In [23]:
np.linalg.solve(A, b)

array([[ 2.6       ],
       [-1.22857143],
       [ 0.71428571]])

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [28]:
import pprint
import scipy
import scipy.linalg

A = scipy.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = scipy.linalg.lu(A)

print(L)
print(U)


[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]
[[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  """


In [31]:
A = scipy.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
P, L, U = scipy.linalg.lu(A)

print(L)
print(U)

[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75       -0.25        1.          0.        ]
 [ 0.25        0.75       -0.17073171  1.        ]]
[[  4.          22.          53.          33.        ]
 [  0.          -6.         -18.5         -7.5       ]
 [  0.           0.         -15.375       -8.625     ]
 [  0.           0.           0.          -0.09756098]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  """Entry point for launching an IPython kernel.


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [32]:
A = scipy.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
P, L, U = scipy.linalg.lu(A)
print(L)
print(U)

[[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]
[[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  """Entry point for launching an IPython kernel.


In [33]:
y1 = 1
y2 = -6 - 0.82
y3 = -5 -0.18 +0.12*y2
print(f'y1: {y1}, y2: {y2}, y3: {y3}')

y1: 1, y2: -6.82, y3: -5.9984


In [34]:
x3 = y3/2.08
x2 = (y2 + 0.09 * x3)/ 2.27
x1 = (y1- 5*x3 - 7*x2)/11
print(f'x1: {x1}, x2: {x2}, x3: {x3}')

x1: 3.38640276023536, x2: -3.1187427990511694, x3: -2.8838461538461537
